export const tagsData = [
  { text: '男', formText: '男', type: 'GENDER' },
  { text: '女', formText: '女', type: 'GENDER' },
  { text: '同省', formText: '同省', type: 'DISTANCE' },
  { text: '地区范围', formText: '地区范围', type: 'DISTANCE' },
  { text: '同城', formText: '同城', type: 'DISTANCE' },
  { text: '同区', formText: '同区', type: 'DISTANCE' },
  { text: '安卓', formText: '安卓', type: 'MOBILE_SYSTEM' },
  { text: '00后', formText: '00后', type: 'PARENTS_AGE' },
  { text: '消费能力中', formText: '消费能力中', type: 'CONSUMPTION_POWER' },
  { text: '90后', formText: '90后', type: 'PARENTS_AGE' },
  { text: '80后', formText: '80后', type: 'PARENTS_AGE' },
  { text: '不限年龄', formText: '不限年龄', type: 'PARENTS_AGE' },
  { text: '70后', formText: '70后', type: 'PARENTS_AGE' },
  { text: '理财高频', formText: '金融理财', type: 'INTEREST_TAG' },
  { text: '游戏高频', formText: '游戏服务', type: 'INTEREST_TAG' },
  { text: '苹果', formText: '苹果', type: 'MOBILE_SYSTEM' },
  { text: '消费能力高', formText: '消费能力高', type: 'CONSUMPTION_POWER' },
  { text: '0~3岁', formText: '0~3岁', type: 'CHILD_AGE' },
  { text: '有子女', formText: '有子女', type: 'HAVE_KIDS' },
  { text: '孕期', formText: '孕期', type: 'CHILD_AGE' },
  { text: '3~6岁', formText: '3~6岁', type: 'CHILD_AGE' },
  { text: '旅行高频', formText: '旅游出行', type: 'INTEREST_TAG' },
  { text: '6~9岁', formText: '6~9岁', type: 'CHILD_AGE' },
  { text: '健身高频', formText: '智能穿戴', type: 'INTEREST_TAG' }
]
