export const getProvinceAbbreviation = (province) => {
  switch (province) {
    case '北京市':
      return '北京'
    case '天津市':
      return '天津'
    case '河北省':
      return '河北'
    case '山西省':
      return '山西'
    case '内蒙古自治区':
      return '内蒙古'
    case '辽宁省':
      return '辽宁'
    case '吉林省':
      return '吉林'
    case '黑龙江省':
      return '黑龙江'
    case '上海市':
      return '上海'
    case '江苏省':
      return '江苏'
    case '浙江省':
      return '浙江'
    case '安徽省':
      return '安徽'
    case '福建省':
      return '福建'
    case '江西省':
      return '江西'
    case '山东省':
      return '山东'
    case '河南省':
      return '河南'
    case '湖北省':
      return '湖北'
    case '湖南省':
      return '湖南'
    case '广东省':
      return '广东'
    case '广西壮族自治区':
      return '广西'
    case '海南省':
      return '海南'
    case '重庆市':
      return '重庆'
    case '四川省':
      return '四川'
    case '贵州省':
      return '贵州'
    case '云南省':
      return '云南'
    case '西藏自治区':
      return '西藏'
    case '陕西省':
      return '陕西'
    case '甘肃省':
      return '甘肃'
    case '青海省':
      return '青海'
    case '宁夏回族自治区':
      return '宁夏'
    case '新疆维吾尔自治区':
      return '新疆'
    case '台湾省':
      return '台湾'
    case '香港特别行政区':
      return '香港'
    case '澳门特别行政区':
      return '澳门'
    default:
      return province
  }
}
